# -*- coding: utf-8 -*-
"""model_2_to2vec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GkgTyxTQPwbIsL9dz95vQGne412vRyw9
"""

!pip install top2vec

!pip install top2vec[sentence_encoders]

!pip install tensorflow tensorflow_hub tensorflow_text

!pip install top2vec tensorflow tensorflow-hub pandas wordcloud

import pandas as pd
from top2vec import Top2Vec
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import tensorflow_hub as hub
import numpy as np

df = pd.read_csv('/content/SMS_train.csv', encoding='latin1')
texts = df['Message_body'].tolist()

# Criação do modelo Top2Vec
embed_model = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

# Instanciar o modelo Top2Vec
model = Top2Vec(texts, embedding_model=embed_model)

# Extração dos tópicos
topics = model.get_topics(2)
topic_indices = [topic[0] for topic in topics]

# Geração da nuvem de palavras
for i, topic in enumerate(topics):
    topic_docs, _, _ = model.search_documents_by_topic(i, num_docs=2)
    topic_text = ' '.join(topic_docs)
    wordcloud = WordCloud(background_color='white').generate(topic_text)
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.show()